# Generated by Django 3.2.5 on 2021-07-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Latest_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=14)),
                ('descendants', models.IntegerField(max_length=10)),
                ('hacker_id', models.IntegerField(max_length=10)),
                ('score', models.IntegerField(max_length=4)),
                ('time', models.IntegerField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('url', models.URLField()),
            ],
        ),
    ]
