# Generated by Django 3.2.5 on 2021-07-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest_news',
            name='descendants',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='latest_news',
            name='hacker_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='latest_news',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='latest_news',
            name='time',
            field=models.IntegerField(),
        ),
    ]
